defaults:
  - dataset: base_dataset
  - trainer: base_trainer
  # - override hydra/job_logging: custom
  # - override hydra/help: clearaudio_help
  - _self_


hydra:
  run:
    dir: ${trainer.base_dir}